### ISSUE TITLE
解析出错

### ISSUE THREAD

**Issue by marklove5102** [cocowool/py-cnblogs#2]
GET https://www.cnblogs.com/h2zZhou/p/12503965.html
Traceback (most recent call last):
  File "sample.py", line 7, in <module>
    b2h.get_cnblogs('https://www.cnblogs.com/h2zZhou/')
  File "/home/freem/博客下载/-好用带图py-cnblogs-master/blog2markdown/blog2html.py", line 47, in get_cnblogs
    self.get_all_posts(lastest_blog_link, url)
  File "/home/freem/博客下载/-好用带图py-cnblogs-master/blog2markdown/blog2html.py", line 72, in get_all_posts
    self.get_all_posts(page_soup.a['href'], home_link)
  File "/home/freem/博客下载/-好用带图py-cnblogs-master/blog2markdown/blog2html.py", line 72, in get_all_posts
    self.get_all_posts(page_soup.a['href'], home_link)
  File "/home/freem/博客下载/-好用带图py-cnblogs-master/blog2markdown/blog2html.py", line 72, in get_all_posts
    self.get_all_posts(page_soup.a['href'], home_link)
  [Previous line repeated 1 more time]
  File "/home/freem/博客下载/-好用带图py-cnblogs-master/blog2markdown/blog2html.py", line 54, in get_all_posts
    print("html.parser :" + str(soup))
  File "/usr/lib/python3.8/site-packages/bs4/element.py", line 1099, in __unicode__
貌似转str 失败。

**Comment by marklove5102** [comment]
self.save_html_file(blog_file_name, html )
投机取巧先把东西拉回来再说。。

**Comment by cocowool** [comment]
感谢提醒，增加了str的支持。
